/* =====================================================================
   EDC Builder - the media library
   ---------------------------------------------------------------------
   GENERATED by scan-media.mjs from the contents of media/stills/.
   Do not edit by hand: drop files in that folder and run

     node tools/edc-builder/scan-media.mjs

   Each entry replaces one product's drawing with an image, everywhere -
   catalogue card, pack list and board. Files are matched by name: the
   product id (bm535.png), or a slug of the brand and name
   (benchmade-bugout-535.png).

   For an image to sit with the drawings around it, cut the background
   out, shoot or generate square-on, and light from the top left. Trim it
   to the object's own edges too: the board fits an image inside the
   product's real millimetre footprint, so a knife centred in a square of
   empty space gets drawn at a third of its true size.

   The app's own picture drop zone does all of that on the way in - this
   file is for images that have already been prepared.

   Pictures a viewer adds in the browser sit on top of whatever is here,
   and removing one reveals this again.

   Empty is the normal state. Nothing here is required.
   ===================================================================== */
window.EDC_MEDIA = {};
