/* =====================================================================
   EDC Builder - the catalog
   ---------------------------------------------------------------------
   One record per product. The fields the rest of the app reads:

     id      stable key. It is what goes in the share link, so renaming
             one breaks every link anyone has already sent. Add, never
             rename.
     name    the product, without the brand
     brand   the maker
     cat     category id from CATS below
     price   typical retail, US dollars
     grams   carried weight, grams. Folders are closed, watches are on
             the strap, sheath knives include the sheath.
     mm      [length, width] of the footprint as the thing lies on a
             board. This drives the layout: the board is drawn at true
             relative scale, so a wrong number here is visible.
     url     the maker's page for it
     art     which drawing generator to use and how to colour it, see
             art.js. Products share generators on purpose - that is what
             makes a board of ninety-odd items look like one photograph
             instead of ninety.
     tags    free text for search and for the loadouts below
     note    one line, why anyone carries it

   Prices and weights are hand-recorded published specs. They go stale.
   See the note on the Share tab, which says so to the user as well.
   ===================================================================== */

const CATS = [
  { id: 'knife',    label: 'Knives',        blurb: 'Folders and fixed blades.' },
  { id: 'multi',    label: 'Multi-tools',   blurb: 'Pliers, drivers and the Swiss Army end of things.' },
  { id: 'light',    label: 'Lights',        blurb: 'Pocket, keychain and headlamps.' },
  { id: 'pen',      label: 'Pens',          blurb: 'Something to write with that survives a pocket.' },
  { id: 'wallet',   label: 'Wallets',       blurb: 'Cards and cash.' },
  { id: 'watch',    label: 'Watches',       blurb: 'Time without unlocking a phone.' },
  { id: 'keys',     label: 'Keys',          blurb: 'Organisers, rings and clips.' },
  { id: 'pry',      label: 'Pry and drive', blurb: 'Small metal for the jobs a knife should not do.' },
  { id: 'fire',     label: 'Fire',          blurb: 'Lighters and sparks.' },
  { id: 'tech',     label: 'Tech',          blurb: 'Power, cable, trackers, audio.' },
  { id: 'paper',    label: 'Paper',         blurb: 'Notebooks and cards.' },
  { id: 'bottle',   label: 'Water',         blurb: 'Bottles and flasks.' },
  { id: 'med',      label: 'Medical',       blurb: 'Boo-boo kit through to bleeding control.' },
  { id: 'pouch',    label: 'Pouches',       blurb: 'What holds the rest of it.' },
  { id: 'eyewear',  label: 'Eyewear',       blurb: 'Sun and safety.' },
  { id: 'belt',     label: 'Belts',         blurb: 'Load-bearing waistline.' },
  { id: 'cord',     label: 'Cord and tape', blurb: 'Line, ties and a flat pack of tape.' },
  { id: 'nav',      label: 'Navigation',    blurb: 'Compass and signal.' },
  { id: 'fidget',   label: 'Fidget',        blurb: 'Pocket toys, for the record.' }
];

/* Shared colourways. Keeping the palette in one place is most of the
   reason the board reads as a single flat-lay rather than a collage. */
const C = {
  steel:    '#c3c8ce',
  steelD:   '#9aa1a9',
  ti:       '#8e8f95',
  brass:    '#c39b52',
  copper:   '#b8724a',
  blackPo:  '#25272b',
  greyPo:   '#4a4e55',
  od:       '#5c6248',
  ranger:   '#77704f',
  coyote:   '#9a7f5d',
  orange:   '#d2691e',
  blaze:    '#e0742c',
  blue:     '#2f5d8c',
  teal:     '#2f7d78',
  red:      '#a93b34',
  maroon:   '#7b3340',
  leather:  '#8a5a34',
  leatherD: '#6a4426',
  kraft:    '#c9b391',
  white:    '#e8e6e1',
  glass:    '#2b3a45'
};

const PRODUCTS = [

  /* ---------------------------- knives ---------------------------- */
  { id:'bm535', name:'Bugout 535', brand:'Benchmade', cat:'knife', price:165, grams:52, mm:[121,31],
    url:'https://www.benchmade.com/', tags:['folder','ultralight','axis','s30v'],
    note:'The reference ultralight folder. You forget it is in the pocket.',
    art:{ kind:'folder', blade:'drop', body:C.od, scale:C.steel, clip:1 } },
  { id:'bm533', name:'Mini Bugout 533', brand:'Benchmade', cat:'knife', price:150, grams:43, mm:[106,28],
    url:'https://www.benchmade.com/', tags:['folder','ultralight','small'],
    note:'The Bugout with the volume turned down. Barely there.',
    art:{ kind:'folder', blade:'drop', body:'#3d5f8a', scale:C.steel, clip:1 } },
  { id:'spypara3', name:'Para 3', brand:'Spyderco', cat:'knife', price:165, grams:106, mm:[109,33],
    url:'https://www.spyderco.com/', tags:['folder','compression lock','thumb hole'],
    note:'Compression lock and a thumb hole you can find with gloves on.',
    art:{ kind:'folder', blade:'leaf', body:C.blackPo, scale:C.steel, clip:1, hole:1 } },
  { id:'spydelica', name:'Delica 4', brand:'Spyderco', cat:'knife', price:110, grams:71, mm:[108,30],
    url:'https://www.spyderco.com/', tags:['folder','lightweight','vg-10'],
    note:'Forty years of people carrying one and not replacing it.',
    art:{ kind:'folder', blade:'leaf', body:'#2f4f77', scale:C.steel, clip:1, hole:1 } },
  { id:'civelem', name:'Elementum', brand:'Civivi', cat:'knife', price:50, grams:96, mm:[105,31],
    url:'https://www.civivi.com/', tags:['folder','budget','gift','liner lock'],
    note:'The one everybody recommends when the budget is fifty dollars.',
    art:{ kind:'folder', blade:'drop', body:C.leather, scale:C.steel, clip:1 } },
  { id:'cjrbpyr', name:'Pyrite', brand:'CJRB', cat:'knife', price:50, grams:100, mm:[100,33],
    url:'https://www.cjrbcutlery.com/', tags:['folder','budget','titanium look'],
    note:'Steel handle, button lock, priced like a gas-station knife is not.',
    art:{ kind:'folder', blade:'wharn', body:C.steelD, scale:C.steel, clip:1 } },
  { id:'kerleek', name:'Leek', brand:'Kershaw', cat:'knife', price:65, grams:85, mm:[102,25],
    url:'https://kershaw.kaiusa.com/', tags:['folder','assisted','slim'],
    note:'Thin, fast and about as inoffensive as a pocket knife gets.',
    art:{ kind:'folder', blade:'trail', body:C.steel, scale:C.steelD, clip:1 } },
  { id:'crktpilar', name:'Pilar', brand:'CRKT', cat:'knife', price:40, grams:116, mm:[83,36],
    url:'https://www.crkt.com/', tags:['folder','stubby','sheepsfoot'],
    note:'Short, fat and stupidly comfortable in a hand doing real work.',
    art:{ kind:'folder', blade:'sheep', body:C.steelD, scale:C.steel } },
  { id:'ratii', name:'RAT II', brand:'Ontario', cat:'knife', price:35, grams:71, mm:[100,30],
    url:'https://www.ontarioknife.com/', tags:['folder','budget','workhorse'],
    note:'The knife you are not sad about losing.',
    art:{ kind:'folder', blade:'drop', body:C.blackPo, scale:C.steel, clip:1 } },
  { id:'opinel8', name:'No. 8 Carbon', brand:'Opinel', cat:'knife', price:18, grams:45, mm:[111,22],
    url:'https://www.opinel.com/', tags:['folder','wood','french','food'],
    note:'A beech handle, a carbon blade and a twist ring. Cuts lunch beautifully.',
    art:{ kind:'opinel', body:C.kraft, scale:C.steel } },
  { id:'moracomp', name:'Companion', brand:'Morakniv', cat:'knife', price:18, grams:120, mm:[218,28],
    url:'https://www.morakniv.se/', tags:['fixed','bushcraft','sheath','budget'],
    note:'More knife per dollar than anything else on the board, sheath included.',
    art:{ kind:'fixed', blade:'drop', body:C.od, sheath:C.blackPo } },
  { id:'eseeizula', name:'Izula', brand:'ESEE', cat:'knife', price:75, grams:55, mm:[165,28],
    url:'https://www.eseeknives.com/', tags:['fixed','neck knife','skeleton'],
    note:'A skeletonised neck knife that carries flat and will not quit.',
    art:{ kind:'fixed', blade:'drop', body:C.blackPo, sheath:C.blackPo, skeleton:1 } },
  { id:'gerbsedge', name:'Sedge', brand:'Gerber', cat:'knife', price:35, grams:27, mm:[89,25],
    url:'https://www.gerbergear.com/', tags:['folder','ultralight','slipjoint'],
    note:'Twenty-seven grams. It disappears in a shirt pocket.',
    art:{ kind:'folder', blade:'drop', body:C.ranger, scale:C.steel } },

  /* -------------------------- multi-tools -------------------------- */
  { id:'ltwaveplus', name:'Wave+', brand:'Leatherman', cat:'multi', price:110, grams:241, mm:[100,34],
    url:'https://www.leatherman.com/', tags:['pliers','outside blades','workhorse'],
    note:'The one everyone pictures when you say multi-tool. Heavy for a reason.',
    art:{ kind:'multitool', body:C.steel, handle:C.steelD, bits:1 } },
  { id:'ltskeleton', name:'Skeletool CX', brand:'Leatherman', cat:'multi', price:95, grams:142, mm:[100,29],
    url:'https://www.leatherman.com/', tags:['pliers','light','bit driver'],
    note:'Pliers, one blade, a bit driver and a bottle opener. Nothing you never use.',
    art:{ kind:'multitool', body:C.steel, handle:C.blackPo, skeleton:1 } },
  { id:'ltfreep4', name:'Free P4', brand:'Leatherman', cat:'multi', price:150, grams:249, mm:[108,38],
    url:'https://www.leatherman.com/', tags:['pliers','magnetic','one hand'],
    note:'Magnets and one-hand opening. The first multi-tool that felt like a nice object.',
    art:{ kind:'multitool', body:C.steel, handle:C.steel, bits:1 } },
  { id:'ltmicra', name:'Micra', brand:'Leatherman', cat:'multi', price:35, grams:51, mm:[65,18],
    url:'https://www.leatherman.com/', tags:['scissors','keychain','tiny'],
    note:'Keychain scissors that actually cut. The rest is a bonus.',
    art:{ kind:'multitool', body:C.steel, handle:C.steel, mini:1 } },
  { id:'vicswisschamp', name:'SwissChamp', brand:'Victorinox', cat:'multi', price:110, grams:185, mm:[91,29],
    url:'https://www.victorinox.com/', tags:['sak','33 functions','red'],
    note:'Thirty-three functions. You will use six and enjoy owning twenty-seven.',
    art:{ kind:'sak', body:C.red, layers:4 } },
  { id:'vicpioneerx', name:'Pioneer X', brand:'Victorinox', cat:'multi', price:60, grams:92, mm:[93,24],
    url:'https://www.victorinox.com/', tags:['sak','alox','scissors'],
    note:'Alox scales, scissors, and a shape that has not needed changing since 1957.',
    art:{ kind:'sak', body:C.steelD, alox:1, layers:2 } },
  { id:'viccadet', name:'Cadet', brand:'Victorinox', cat:'multi', price:40, grams:47, mm:[84,20],
    url:'https://www.victorinox.com/', tags:['sak','alox','slim','flat'],
    note:'Flat, light, and the least intimidating blade you can put on a table.',
    art:{ kind:'sak', body:C.steelD, alox:1, layers:1 } },
  { id:'vicclassic', name:'Classic SD', brand:'Victorinox', cat:'multi', price:22, grams:21, mm:[58,18],
    url:'https://www.victorinox.com/', tags:['sak','keychain','scissors','tweezers'],
    note:'Lives on a keyring for a decade and pays for itself in loose threads.',
    art:{ kind:'sak', body:C.red, layers:1, small:1 } },
  { id:'gerbdime', name:'Dime', brand:'Gerber', cat:'multi', price:25, grams:62, mm:[73,28],
    url:'https://www.gerbergear.com/', tags:['pliers','keychain','budget'],
    note:'Keychain pliers with a package opener that is better than it sounds.',
    art:{ kind:'multitool', body:C.steel, handle:C.blue, mini:1 } },
  { id:'sogpower', name:'PowerAccess', brand:'SOG', cat:'multi', price:50, grams:149, mm:[102,33],
    url:'https://www.sog.com/', tags:['pliers','compound leverage','budget'],
    note:'Compound leverage jaws for the price of a nice lunch.',
    art:{ kind:'multitool', body:C.steelD, handle:C.steelD, bits:1 } },

  /* ---------------------------- lights ---------------------------- */
  { id:'olbaton4', name:'Baton 4', brand:'Olight', cat:'light', price:80, grams:53, mm:[62,22],
    url:'https://www.olightstore.com/', tags:['1300 lumens','magnetic','rechargeable','pocket'],
    note:'Tiny, absurdly bright, and the magnet in the tailcap earns its keep.',
    art:{ kind:'lightTube', body:C.blackPo, bezel:C.steel, len:62, dia:22 } },
  { id:'oli3t', name:'i3T EOS', brand:'Olight', cat:'light', price:22, grams:41, mm:[93,14],
    url:'https://www.olightstore.com/', tags:['aaa','tail switch','slim','budget'],
    note:'A single AAA, a tail click, and a clip that lives in a pocket seam.',
    art:{ kind:'lightTube', body:C.od, bezel:C.steel, len:93, dia:14, clip:1 } },
  { id:'slmicro', name:'MicroStream USB', brand:'Streamlight', cat:'light', price:40, grams:45, mm:[105,17],
    url:'https://www.streamlight.com/', tags:['rechargeable','pen light','clip','250 lumens'],
    note:'Pen-shaped, USB, and it clips in a shirt pocket without shouting about it.',
    art:{ kind:'lightTube', body:C.blackPo, bezel:C.steelD, len:105, dia:17, clip:1 } },
  { id:'slprotac', name:'ProTac 1L-1AA', brand:'Streamlight', cat:'light', price:60, grams:78, mm:[122,22],
    url:'https://www.streamlight.com/', tags:['dual fuel','cr123','aa','duty'],
    note:'Runs on a CR123 or an AA. That flexibility is the whole pitch.',
    art:{ kind:'lightTube', body:C.blackPo, bezel:C.steel, len:122, dia:22, clip:1, knurl:1 } },
  { id:'sfstiletto', name:'Stiletto', brand:'SureFire', cat:'light', price:110, grams:79, mm:[117,28],
    url:'https://www.surefire.com/', tags:['flat','rechargeable','duty','650 lumens'],
    note:'Flat instead of round, so it lies in a pocket instead of rolling around it.',
    art:{ kind:'lightFlat', body:C.blackPo, bezel:C.steelD } },
  { id:'fenixpd36r', name:'PD36R Pro', brand:'Fenix', cat:'light', price:110, grams:145, mm:[140,26],
    url:'https://www.fenixlighting.com/', tags:['2800 lumens','usb-c','thrower'],
    note:'Genuinely too much light for a pocket, which is exactly why people carry it.',
    art:{ kind:'lightTube', body:C.blackPo, bezel:C.steel, len:140, dia:26, clip:1, knurl:1 } },
  { id:'fenixe12', name:'E12 V2.0', brand:'Fenix', cat:'light', price:35, grams:40, mm:[92,20],
    url:'https://www.fenixlighting.com/', tags:['aa','simple','budget'],
    note:'One AA, three modes, no menu to learn.',
    art:{ kind:'lightTube', body:C.blackPo, bezel:C.steelD, len:92, dia:20, clip:1 } },
  { id:'nctip', name:'TIP SE', brand:'Nitecore', cat:'light', price:30, grams:32, mm:[60,25],
    url:'https://www.nitecore.com/', tags:['keychain','rechargeable','flat'],
    note:'Flat keychain light that will not put a hole in a pocket lining.',
    art:{ kind:'lightKey', body:C.steelD, bezel:C.steel } },
  { id:'nctini2', name:'TINI 2', brand:'Nitecore', cat:'light', price:35, grams:25, mm:[53,22],
    url:'https://www.nitecore.com/', tags:['keychain','oled','tiny'],
    note:'Twenty-five grams with a little screen on it, because why not.',
    art:{ kind:'lightKey', body:C.blackPo, bezel:C.steel, screen:1 } },
  { id:'rvaurora', name:'Aurora A5', brand:'RovyVon', cat:'light', price:50, grams:25, mm:[61,18],
    url:'https://www.rovyvon.com/', tags:['keychain','uv','glow','rechargeable'],
    note:'A keychain light with side glow and a UV mode, which is more useful than it sounds.',
    art:{ kind:'lightKey', body:'#2c3a30', bezel:C.steel, glow:1 } },
  { id:'zebrasc64', name:'SC64c LE', brand:'ZebraLight', cat:'light', price:95, grams:80, mm:[82,25],
    url:'https://www.zebralight.com/', tags:['right angle','18650','high cri','headlamp'],
    note:'Right-angle body clips to a pocket and points where you are looking.',
    art:{ kind:'lightAngle', body:C.blackPo, bezel:C.steel } },
  { id:'petzlbindi', name:'Bindi', brand:'Petzl', cat:'light', price:60, grams:35, mm:[62,42],
    url:'https://www.petzl.com/', tags:['headlamp','ultralight','rechargeable'],
    note:'Thirty-five grams of headlamp on a cord. Both hands stay free.',
    art:{ kind:'headlamp', body:C.blackPo, bezel:C.steel, band:C.greyPo } },

  /* ----------------------------- pens ----------------------------- */
  { id:'fisherbullet', name:'Bullet Space Pen', brand:'Fisher', cat:'pen', price:30, grams:26, mm:[95,10],
    url:'https://www.spacepen.com/', tags:['pressurised','upside down','tiny','chrome'],
    note:'Ninety-five millimetres closed, writes upside down and in the wet.',
    art:{ kind:'pen', body:C.steel, tip:C.steelD, len:95, dia:10, bullet:1 } },
  { id:'ttsideclick', name:'Side Click Standard', brand:'Tactile Turn', cat:'pen', price:99, grams:33, mm:[137,11],
    url:'https://tactileturn.com/', tags:['titanium','machined','side click'],
    note:'Machined ridges you can feel through a glove, and a click on the side.',
    art:{ kind:'pen', body:C.ti, tip:C.ti, len:137, dia:11, ridges:1, clip:1 } },
  { id:'bidtipocket', name:'Ti Pocket Pro', brand:'Big Idea Design', cat:'pen', price:89, grams:27, mm:[89,12],
    url:'https://www.bigidesign.com/', tags:['titanium','bolt action','short'],
    note:'Bolt action, pocket length, and it takes almost any refill.',
    art:{ kind:'pen', body:C.ti, tip:C.ti, len:89, dia:12, bolt:1, clip:1 } },
  { id:'ritrpen', name:'All-Weather Pen', brand:'Rite in the Rain', cat:'pen', price:25, grams:21, mm:[140,11],
    url:'https://www.riteintherain.com/', tags:['wet','ink','pressurised','field'],
    note:'Pairs with the notebook. Writes on paper that is already soaked.',
    art:{ kind:'pen', body:C.blaze, tip:C.blackPo, len:140, dia:11, clip:1 } },
  { id:'zebraf701', name:'F-701', brand:'Zebra', cat:'pen', price:18, grams:26, mm:[140,11],
    url:'https://zebrapen.com/', tags:['stainless','knurled','cheap','mod'],
    note:'Stainless and knurled for the price of a sandwich. The classic modding platform.',
    art:{ kind:'pen', body:C.steel, tip:C.steelD, len:140, dia:11, ridges:1, clip:1 } },
  { id:'karasrenderk', name:'Render K', brand:'Karas Kustoms', cat:'pen', price:60, grams:28, mm:[135,11],
    url:'https://www.karaskustoms.com/', tags:['aluminium','machined','usa'],
    note:'Machined aluminium, a proper click, and it takes a Pilot G2 refill.',
    art:{ kind:'pen', body:C.blue, tip:C.steelD, len:135, dia:11, clip:1 } },
  { id:'unijetstream', name:'Jetstream 0.7', brand:'Uni-ball', cat:'pen', price:4, grams:12, mm:[145,11],
    url:'https://www.uniball.com/', tags:['refill','smooth','cheap','best ink'],
    note:'Beaten on looks by everything here and beaten on ink by almost nothing.',
    art:{ kind:'pen', body:C.white, tip:C.blackPo, len:145, dia:11, clip:1 } },

  /* ---------------------------- wallets ---------------------------- */
  { id:'ridgealu', name:'Aluminum Wallet', brand:'Ridge', cat:'wallet', price:95, grams:86, mm:[86,54],
    url:'https://ridge.com/', tags:['metal','money clip','rfid','minimal'],
    note:'Two plates and a band. Holds a dozen cards and refuses to get fat.',
    art:{ kind:'walletCard', body:C.steelD, band:C.blackPo, metal:1 } },
  { id:'bellrynote', name:'Note Sleeve', brand:'Bellroy', cat:'wallet', price:99, grams:60, mm:[105,77],
    url:'https://bellroy.com/', tags:['leather','bifold','slim','cash'],
    note:'A bifold that stays thin because it was designed around eleven cards, not forty.',
    art:{ kind:'walletBi', body:C.leather, stitch:'#d8c39a' } },
  { id:'trayvaxelem', name:'Element', brand:'Trayvax', cat:'wallet', price:75, grams:90, mm:[95,60],
    url:'https://trayvax.com/', tags:['steel','paracord','rugged','bottle opener'],
    note:'Steel plate, paracord lashing, and it will outlive the trousers.',
    art:{ kind:'walletCard', body:C.ranger, band:C.blackPo, metal:1, cord:1 } },
  { id:'eksteralu', name:'Aluminum Cardholder', brand:'Ekster', cat:'wallet', price:89, grams:65, mm:[96,61],
    url:'https://ekster.com/', tags:['fan out','rfid','leather','trigger'],
    note:'Press the lever and the cards fan out. Genuinely faster at a till.',
    art:{ kind:'walletCard', body:C.blackPo, band:C.leatherD, metal:1, fan:1 } },
  { id:'nomadslim', name:'Slim Wallet', brand:'Nomad', cat:'wallet', price:60, grams:35, mm:[105,75],
    url:'https://nomadgoods.com/', tags:['horween','leather','patina','slim'],
    note:'Horween leather that looks better in year three than year one.',
    art:{ kind:'walletBi', body:C.leatherD, stitch:'#c8a878' } },
  { id:'machineera', name:'Card Caddy', brand:'Machine Era', cat:'wallet', price:45, grams:40, mm:[87,55],
    url:'https://machineeraco.com/', tags:['aluminium','minimal','usa','anodised'],
    note:'A single milled block with a band. Nothing to wear out.',
    art:{ kind:'walletCard', body:C.teal, band:C.blackPo, metal:1 } },

  /* ---------------------------- watches ---------------------------- */
  { id:'gshock5600', name:'G-Shock DW-5600E', brand:'Casio', cat:'watch', price:60, grams:53, mm:[48,78],
    url:'https://www.casio.com/', tags:['digital','indestructible','square','resin'],
    note:'The square. Nothing at this price has survived more abuse in more countries.',
    art:{ kind:'watchDigital', body:C.blackPo, face:'#4c5a4e', band:C.blackPo, square:1 } },
  { id:'casiof91w', name:'F-91W', brand:'Casio', cat:'watch', price:20, grams:21, mm:[37,68],
    url:'https://www.casio.com/', tags:['digital','ultralight','cheap','iconic'],
    note:'Twenty-one grams, a decade of battery, and utterly unbothered.',
    art:{ kind:'watchDigital', body:C.blackPo, face:'#5a6a58', band:C.blackPo } },
  { id:'casioa168', name:'A168W', brand:'Casio', cat:'watch', price:35, grams:66, mm:[38,72],
    url:'https://www.casio.com/', tags:['digital','steel bracelet','retro'],
    note:'Steel bracelet, eighties lines, costs less than a pair of shoes.',
    art:{ kind:'watchDigital', body:C.steel, face:'#4a5a5f', band:C.steelD, bracelet:1 } },
  { id:'seiko5snk', name:'5 SNK809', brand:'Seiko', cat:'watch', price:130, grams:65, mm:[37,72],
    url:'https://www.seikowatches.com/', tags:['automatic','field','canvas','no battery'],
    note:'An automatic field watch. Wear it and it never needs a battery.',
    art:{ kind:'watchAnalog', body:C.steel, face:C.blackPo, band:C.od } },
  { id:'timexweek', name:'Weekender', brand:'Timex', cat:'watch', price:45, grams:40, mm:[38,73],
    url:'https://www.timex.com/', tags:['quartz','nato','indiglo','cheap'],
    note:'Swap the NATO strap and it is a different watch for eight dollars.',
    art:{ kind:'watchAnalog', body:C.steel, face:C.white, band:C.ranger, light:1 } },
  { id:'protrek3400', name:'Pro Trek PRW-3400', brand:'Casio', cat:'watch', price:300, grams:62, mm:[51,82],
    url:'https://www.casio.com/', tags:['solar','altimeter','compass','barometer'],
    note:'Solar, atomic, and it tells you the air pressure is dropping before the sky does.',
    art:{ kind:'watchDigital', body:C.blackPo, face:'#3f5a52', band:C.blackPo, big:1 } },
  { id:'garmininst2', name:'Instinct 2', brand:'Garmin', cat:'watch', price:300, grams:52, mm:[45,80],
    url:'https://www.garmin.com/', tags:['gps','solar','rugged','smart'],
    note:'GPS and weeks of battery, which is the trade most smartwatches refuse to make.',
    art:{ kind:'watchDigital', body:C.od, face:'#7c8474', band:C.od, round:1 } },
  { id:'marathonnav', name:'Navigator', brand:'Marathon', cat:'watch', price:200, grams:43, mm:[41,76],
    url:'https://www.marathonwatch.com/', tags:['tritium','issue','fibreshell','24 hour'],
    note:'Tritium tubes that glow for years without ever being charged by light.',
    art:{ kind:'watchAnalog', body:C.blackPo, face:C.blackPo, band:C.blackPo, tritium:1 } },

  /* ----------------------------- keys ----------------------------- */
  { id:'keybaralu', name:'KeyBar Aluminum', brand:'KeyBar', cat:'keys', price:45, grams:60, mm:[90,25],
    url:'https://keybar.us/', tags:['organiser','pivot','quiet','clip'],
    note:'Keys fan out of a body like a pocket knife. No jangling.',
    art:{ kind:'keyOrg', body:C.steelD, keys:C.brass } },
  { id:'keysmartpro', name:'KeySmart Pro', brand:'KeySmart', cat:'keys', price:60, grams:60, mm:[89,25],
    url:'https://www.getkeysmart.com/', tags:['organiser','tile','light','tracker'],
    note:'Organiser with a tracker and a light built in, so the keys find themselves.',
    art:{ kind:'keyOrg', body:C.blackPo, keys:C.steel, led:1 } },
  { id:'orbitring', name:'Ring V2', brand:'Orbitkey', cat:'keys', price:25, grams:12, mm:[42,42],
    url:'https://www.orbitkey.com/', tags:['ring','quick release','no fingernails'],
    note:'A key ring you can open without sacrificing a fingernail.',
    art:{ kind:'ring', body:C.steel } },
  { id:'sbiner2', name:'S-Biner #2', brand:'Nite Ize', cat:'keys', price:4, grams:6, mm:[47,22],
    url:'https://www.niteize.com/', tags:['carabiner','cheap','double gate'],
    note:'Four dollars. Clips one thing to another thing, forever.',
    art:{ kind:'sbiner', body:C.steel } },
  { id:'ccbolt', name:'Bolt Action Bottle Opener', brand:'CountyComm', cat:'keys', price:14, grams:18, mm:[62,14],
    url:'https://countycomm.com/', tags:['brass','opener','keychain','fidget'],
    note:'Opens bottles and is quietly the best fidget on this whole board.',
    art:{ kind:'barTool', body:C.brass, len:62, wid:14 } },

  /* --------------------------- pry / drive --------------------------- */
  { id:'ccwidgy4', name:'Widgy Pry Bar 4"', brand:'CountyComm', cat:'pry', price:14, grams:26, mm:[102,14],
    url:'https://countycomm.com/', tags:['pry','titanium','cheap','staple puller'],
    note:'Saves a knife tip from every job a knife tip should never do.',
    art:{ kind:'pry', body:C.ti, len:102, wid:14 } },
  { id:'ccmicrowidgy', name:'Micro Widgy', brand:'CountyComm', cat:'pry', price:12, grams:12, mm:[76,12],
    url:'https://countycomm.com/', tags:['pry','keychain','tiny'],
    note:'The Widgy that fits on a keyring next to a house key.',
    art:{ kind:'pry', body:C.ti, len:76, wid:12 } },
  { id:'gerbshard', name:'Shard', brand:'Gerber', cat:'pry', price:10, grams:15, mm:[76,22],
    url:'https://www.gerbergear.com/', tags:['flat','airport friendly','driver','opener'],
    note:'No blade, so it clears airport security. Seven functions in a flat bit of steel.',
    art:{ kind:'shard', body:C.blackPo } },
  { id:'werabitcheck', name:'Bit-Check 6', brand:'Wera', cat:'pry', price:25, grams:60, mm:[85,32],
    url:'https://www.wera.de/', tags:['bits','driver','pocket'],
    note:'Six bits in a hard case. It weighs nothing and it fixes furniture.',
    art:{ kind:'bitCase', body:C.blackPo, accent:'#2c7c3f' } },
  { id:'chapmanmini', name:'Mini Ratchet Set', brand:'Chapman', cat:'pry', price:40, grams:90, mm:[110,60],
    url:'https://www.chapmanmfg.com/', tags:['ratchet','bits','usa','glasses'],
    note:'A tiny ratchet and a fan of bits, made in Connecticut since the sixties.',
    art:{ kind:'bitCase', body:C.steelD, accent:C.red, ratchet:1 } },

  /* ----------------------------- fire ----------------------------- */
  { id:'bicmini', name:'Mini Lighter', brand:'Bic', cat:'fire', price:2, grams:11, mm:[68,22],
    url:'https://www.bic.com/', tags:['lighter','cheap','reliable','disposable'],
    note:'Two dollars and it works. Nothing here has a better ratio.',
    art:{ kind:'lighterBic', body:C.blaze } },
  { id:'zippoclassic', name:'Classic Chrome', brand:'Zippo', cat:'fire', price:30, grams:62, mm:[56,38],
    url:'https://www.zippo.com/', tags:['lighter','windproof','refillable','clink'],
    note:'Windproof, refillable, and the noise it makes is half the point.',
    art:{ kind:'lighterZippo', body:C.steel } },
  { id:'exonano', name:'nanoSTRIKER XL', brand:'Exotac', cat:'fire', price:40, grams:28, mm:[76,14],
    url:'https://exotac.com/', tags:['ferro rod','wet','backup','machined'],
    note:'Ferro rod and striker that stow inside each other. Works soaked.',
    art:{ kind:'ferro', body:C.blackPo, rod:C.steelD } },
  { id:'exofirerod', name:'fireROD XL', brand:'Exotac', cat:'fire', price:30, grams:30, mm:[90,14],
    url:'https://exotac.com/', tags:['ferro rod','tinder','waterproof'],
    note:'A ferro rod with a waterproof tinder capsule in the handle.',
    art:{ kind:'ferro', body:C.od, rod:C.steelD, capsule:1 } },

  /* ----------------------------- tech ----------------------------- */
  { id:'ncnb10000', name:'NB10000 Gen3', brand:'Nitecore', cat:'tech', price:60, grams:150, mm:[137,72],
    url:'https://www.nitecore.com/', tags:['power bank','carbon fibre','10000mah','light'],
    note:'Ten thousand milliamp hours in a carbon shell at 150 grams. Absurd.',
    art:{ kind:'powerBank', body:'#20242a', accent:C.steelD, carbon:1 } },
  { id:'ankernano5k', name:'Nano Power Bank 5K', brand:'Anker', cat:'tech', price:50, grams:100, mm:[92,44],
    url:'https://www.anker.com/', tags:['power bank','built in cable','phone top up'],
    note:'The plug is built in, so the cable you forgot does not matter.',
    art:{ kind:'powerBank', body:C.white, accent:C.blue, small:1 } },
  { id:'anker511', name:'511 Nano 3 Charger', brand:'Anker', cat:'tech', price:20, grams:32, mm:[36,30],
    url:'https://www.anker.com/', tags:['charger','30w','tiny','gan'],
    note:'Thirty watts the size of a wall socket screw cap.',
    art:{ kind:'charger', body:C.white, accent:C.teal } },
  { id:'nomadcable', name:'Universal Cable 1.5m', brand:'Nomad', cat:'tech', price:30, grams:45, mm:[90,90],
    url:'https://nomadgoods.com/', tags:['usb-c','kevlar','durable','coiled'],
    note:'Kevlar-reinforced, so it survives being wound around a power bank forever.',
    art:{ kind:'cable', body:C.blackPo, ends:C.steelD } },
  { id:'airtag', name:'AirTag', brand:'Apple', cat:'tech', price:29, grams:11, mm:[32,32],
    url:'https://www.apple.com/', tags:['tracker','find my','bag','keys'],
    note:'Goes in the bag you would be most upset to lose.',
    art:{ kind:'tracker', body:C.white, accent:C.steel, round:1 } },
  { id:'chipoloone', name:'ONE Point', brand:'Chipolo', cat:'tech', price:25, grams:6, mm:[38,38],
    url:'https://chipolo.net/', tags:['tracker','android','loud','keys'],
    note:'The Android answer to an AirTag, and considerably louder.',
    art:{ kind:'tracker', body:C.blue, accent:C.white, round:1 } },
  { id:'airpodspro', name:'AirPods Pro case', brand:'Apple', cat:'tech', price:249, grams:51, mm:[46,61],
    url:'https://www.apple.com/', tags:['earbuds','anc','case','audio'],
    note:'Noise cancelling in a case the size of a dental floss box.',
    art:{ kind:'budCase', body:C.white } },
  { id:'sandiskusb', name:'Ultra Dual Drive 128GB', brand:'SanDisk', cat:'tech', price:20, grams:3, mm:[40,12],
    url:'https://www.sandisk.com/', tags:['usb-c','flash','files','tiny'],
    note:'Three grams. The moment you need it you will be very pleased with yourself.',
    art:{ kind:'usbStick', body:C.blackPo, accent:C.steel } },

  /* ---------------------------- paper ---------------------------- */
  { id:'fieldnotes', name:'Original Kraft', brand:'Field Notes', cat:'paper', price:5, grams:22, mm:[89,140],
    url:'https://fieldnotesbrand.com/', tags:['notebook','kraft','pocket','graph'],
    note:'Kraft cover, forty-eight pages, and it fits a back pocket without complaint.',
    art:{ kind:'notebook', body:C.kraft, band:'#6f5c3d' } },
  { id:'ritr391', name:'No. 391 Memo', brand:'Rite in the Rain', cat:'paper', price:9, grams:30, mm:[76,127],
    url:'https://www.riteintherain.com/', tags:['notebook','waterproof','field','yellow'],
    note:'Write on it in the rain. That is not marketing, it just works.',
    art:{ kind:'notebook', body:'#c8a93a', band:'#8a7326' } },
  { id:'moleskinecahier', name:'Cahier Pocket', brand:'Moleskine', cat:'paper', price:6, grams:40, mm:[90,140],
    url:'https://www.moleskine.com/', tags:['notebook','soft','stitched','cheap'],
    note:'Card cover, visible stitching, lies flat and costs almost nothing.',
    art:{ kind:'notebook', body:C.leatherD, band:'#4d3520' } },
  { id:'wordnotebook', name:'Bullet Journal 3-pack', brand:'Word.', cat:'paper', price:10, grams:25, mm:[89,140],
    url:'https://wordnotebooks.com/', tags:['notebook','bullet','list','pocket'],
    note:'Pre-printed bullets down the page for people who write in lists.',
    art:{ kind:'notebook', body:C.white, band:C.red } },

  /* ---------------------------- bottle ---------------------------- */
  { id:'nalgene32', name:'Wide Mouth 32oz', brand:'Nalgene', cat:'bottle', price:16, grams:178, mm:[90,216],
    url:'https://nalgene.com/', tags:['bottle','indestructible','markings','wide'],
    note:'Indestructible, has never once leaked, and everyone knows what it is.',
    art:{ kind:'bottle', body:'#4a7f9a', cap:C.blackPo, translucent:1, wide:1 } },
  { id:'hydro21', name:'Standard Mouth 21oz', brand:'Hydro Flask', cat:'bottle', price:35, grams:340, mm:[73,250],
    url:'https://www.hydroflask.com/', tags:['bottle','insulated','cold','steel'],
    note:'Ice at the end of a shift. Costs you 340 grams to get it.',
    art:{ kind:'bottle', body:C.teal, cap:C.blackPo } },
  { id:'kkTKwide16', name:'TKWide 16oz', brand:'Klean Kanteen', cat:'bottle', price:35, grams:300, mm:[73,170],
    url:'https://www.kleankanteen.com/', tags:['bottle','insulated','cafe cap','steel'],
    note:'The café cap makes it a travel mug without buying a travel mug.',
    art:{ kind:'bottle', body:C.steelD, cap:C.blackPo } },
  { id:'vargobot700', name:'Titanium BOT 700', brand:'Vargo', cat:'bottle', price:90, grams:136, mm:[95,145],
    url:'https://vargooutdoors.com/', tags:['titanium','cook pot','bottle','ultralight'],
    note:'A bottle you can also boil water in. Two things, one 136 gram object.',
    art:{ kind:'bottle', body:C.ti, cap:C.ti, wide:1 } },

  /* ---------------------------- medical ---------------------------- */
  { id:'catgen7', name:'C-A-T Gen 7 Tourniquet', brand:'North American Rescue', cat:'med', price:32, grams:76, mm:[165,55],
    url:'https://www.narescue.com/', tags:['tourniquet','bleeding','trauma','cat'],
    note:'The single item on this board most likely to save a life. Get trained on it.',
    art:{ kind:'tourniquet', body:C.blackPo, windlass:C.blackPo } },
  { id:'izzybandage', name:'Emergency Bandage 4"', brand:'PerSys', cat:'med', price:12, grams:105, mm:[130,70],
    url:'https://www.persysmedical.com/', tags:['pressure','trauma','israeli','wound'],
    note:'Pressure bandage in a vacuum pack. Flat, cheap, and it keeps for years.',
    art:{ kind:'medPack', body:C.white, accent:C.od } },
  { id:'amk05', name:'Ultralight/Watertight .5', brand:'Adventure Medical', cat:'med', price:12, grams:90, mm:[130,90],
    url:'https://www.adventuremedicalkits.com/', tags:['first aid','blisters','ultralight','kit'],
    note:'The everyday cuts-and-blisters kit, sealed against rain.',
    art:{ kind:'medPack', body:C.red, accent:C.white, cross:1 } },
  { id:'chestseal', name:'HyFin Vent Chest Seal', brand:'North American Rescue', cat:'med', price:20, grams:35, mm:[140,100],
    url:'https://www.narescue.com/', tags:['trauma','penetrating','vented','seal'],
    note:'Twin pack, vented. Part of any kit that already carries a tourniquet.',
    art:{ kind:'medPack', body:'#2a2f36', accent:C.orange } },

  /* ---------------------------- pouches ---------------------------- */
  { id:'maxpedmpo', name:'Micro Pocket Organizer', brand:'Maxpedition', cat:'pouch', price:30, grams:100, mm:[175,125],
    url:'https://www.maxpedition.com/', tags:['organiser','elastic','pockets','nylon'],
    note:'Elastic loops for everything small, so it stops rattling round a bag.',
    art:{ kind:'pouch', body:C.blackPo, zip:C.steelD } },
  { id:'vanquestedcm', name:'EDCM-Slim', brand:'Vanquest', cat:'pouch', price:40, grams:120, mm:[180,120],
    url:'https://www.vanquest.com/', tags:['organiser','slim','molle','admin'],
    note:'Same idea as the Maxpedition, laid out flatter for a jacket pocket.',
    art:{ kind:'pouch', body:C.ranger, zip:C.steelD } },
  { id:'tombihnghost', name:'Ghost Whale Organizer', brand:'Tom Bihn', cat:'pouch', price:28, grams:30, mm:[150,100],
    url:'https://www.tombihn.com/', tags:['pouch','light','clear','usa'],
    note:'Thirty grams, made in Seattle, and you can see what is inside it.',
    art:{ kind:'pouch', body:'#3b6d7c', zip:C.steel, clear:1 } },
  { id:'peaktech', name:'Tech Pouch', brand:'Peak Design', cat:'pouch', price:60, grams:300, mm:[230,120],
    url:'https://www.peakdesign.com/', tags:['origami','cables','travel','premium'],
    note:'Origami shelves inside. Overkill for a pocket, perfect for a bag.',
    art:{ kind:'pouch', body:'#3a3f47', zip:C.steel, big:1 } },

  /* ---------------------------- eyewear ---------------------------- */
  { id:'oakholbrook', name:'Holbrook', brand:'Oakley', cat:'eyewear', price:150, grams:30, mm:[140,48],
    url:'https://www.oakley.com/', tags:['sunglasses','prizm','impact','classic'],
    note:'Impact rated and shaped so they suit most faces. That is the whole trick.',
    art:{ kind:'shades', body:C.blackPo, lens:'#4a5f6d' } },
  { id:'gatorzmagnum', name:'Magnum', brand:'Gatorz', cat:'eyewear', price:200, grams:34, mm:[145,50],
    url:'https://gatorz.com/', tags:['aluminium','bendable','ballistic','usa'],
    note:'Aluminium frames you can bend back to fit your head. Literally.',
    art:{ kind:'shades', body:C.steelD, lens:'#3d4d3f' } },
  { id:'knockpremium', name:'Premiums', brand:'Knockaround', cat:'eyewear', price:30, grams:25, mm:[140,46],
    url:'https://knockaround.com/', tags:['cheap','polarised','lose them','colours'],
    note:'Cheap enough that losing a pair is an inconvenience, not an event.',
    art:{ kind:'shades', body:C.maroon, lens:'#5a4a3a' } },

  /* ----------------------------- belts ----------------------------- */
  { id:'bluealphaedc', name:'EDC Belt', brand:'Blue Alpha', cat:'belt', price:60, grams:150, mm:[125,125],
    url:'https://bluealphabelts.com/', tags:['nylon','cobra','holster','stiff'],
    note:'Stiff enough to hang tools off, soft enough to wear to dinner.',
    art:{ kind:'belt', body:C.blackPo, buckle:C.steelD } },
  { id:'korerachet', name:'Ratchet Belt', brand:'Kore Essentials', cat:'belt', price:50, grams:140, mm:[125,125],
    url:'https://www.koreessentials.com/', tags:['ratchet','micro adjust','leather'],
    note:'No holes, so it adjusts in quarter-inch steps instead of inch ones.',
    art:{ kind:'belt', body:C.leatherD, buckle:C.steel } },
  { id:'nexbeltedc', name:'Titan EDC', brand:'Nexbelt', cat:'belt', price:60, grams:130, mm:[125,125],
    url:'https://www.nexbelt.com/', tags:['ratchet','nylon','carry','stiff'],
    note:'The ratchet idea again, in nylon, built around carrying weight.',
    art:{ kind:'belt', body:C.ranger, buckle:C.blackPo } },

  /* -------------------------- cord and tape -------------------------- */
  { id:'gorillaflat', name:'Tape, flat pack 3m', brand:'Gorilla', cat:'cord', price:6, grams:30, mm:[80,50],
    url:'https://www.gorillatough.com/', tags:['tape','repair','flat','wrap'],
    note:'Wound flat instead of on a roll, so it lies in a pouch.',
    art:{ kind:'tapeFlat', body:'#2f3237', accent:C.white } },
  { id:'paracord10', name:'550 Paracord, 3m hank', brand:'Atwood', cat:'cord', price:4, grams:25, mm:[90,35],
    url:'https://www.atwoodrope.com/', tags:['cord','550','repair','lashing'],
    note:'Seven inner strands. It is nine different pieces of string.',
    art:{ kind:'cordHank', body:C.od } },
  { id:'geartie6', name:'Gear Tie 6", pair', brand:'Nite Ize', cat:'cord', price:5, grams:12, mm:[152,10],
    url:'https://www.niteize.com/', tags:['twist tie','rubber','reusable','cable'],
    note:'Rubber over wire. Bends, holds, and is not a single-use zip tie.',
    art:{ kind:'gearTie', body:C.blaze } },

  /* -------------------------- navigation -------------------------- */
  { id:'suuntoclipper', name:'Clipper Compass', brand:'Suunto', cat:'nav', price:25, grams:12, mm:[32,26],
    url:'https://www.suunto.com/', tags:['compass','watchband','tiny','backup'],
    note:'Clips to a watch strap and settles fast. Twelve grams of no-battery direction.',
    art:{ kind:'compass', body:C.blackPo, dial:C.white } },
  { id:'silvaranger', name:'Ranger 2.0', brand:'Silva', cat:'nav', price:60, grams:55, mm:[125,65],
    url:'https://www.silva.se/', tags:['compass','baseplate','map','declination'],
    note:'A real baseplate compass. Useless without a map, essential with one.',
    art:{ kind:'compassPlate', body:'#3a4750', dial:C.white } },
  { id:'fox40whistle', name:'Micro Whistle', brand:'Fox 40', cat:'nav', price:8, grams:8, mm:[45,20],
    url:'https://www.fox40world.com/', tags:['whistle','pealess','signal','loud'],
    note:'Pealess, so it works wet, and it carries a lot further than shouting.',
    art:{ kind:'whistle', body:C.orange } },

  /* ---------------------------- fidget ---------------------------- */
  { id:'begleri', name:'Titanium Begleri', brand:'Aroundsquare', cat:'fidget', price:35, grams:38, mm:[110,16],
    url:'https://aroundsquare.com/', tags:['fidget','skill toy','titanium','beads'],
    note:'Two beads on a cord. Quiet, and it does not roll off a desk.',
    art:{ kind:'begleri', body:C.ti } },
  { id:'tispinner', name:'Titanium Spinner', brand:'Generic', cat:'fidget', price:40, grams:40, mm:[45,45],
    url:'https://countycomm.com/', tags:['fidget','bearing','spin','desk'],
    note:'Yes, still. It is a bearing in a bit of metal and it is oddly calming.',
    art:{ kind:'spinner', body:C.ti } },
  { id:'ccclicker', name:'Brass Clicker', brand:'CountyComm', cat:'fidget', price:12, grams:22, mm:[38,24],
    url:'https://countycomm.com/', tags:['fidget','brass','click','patina'],
    note:'Clicks. Develops a patina. There is no more to it than that.',
    art:{ kind:'barTool', body:C.brass, len:38, wid:24 } }

];

/* One-click starting points. Each is a list of product ids; the app
   drops them straight into the pack so a new user has something on the
   board inside five seconds. */
const LOADOUTS = [
  { id:'minimal', name:'Minimalist', blurb:'Five things, nothing you would notice carrying.',
    items:['bm533','nctini2','viccadet','ridgealu','casiof91w'] },
  { id:'trades', name:'On the tools', blurb:'A working day, in a work trouser pocket.',
    items:['ltwaveplus','slprotac','ratii','ritrpen','ritr391','gshock5600','bluealphaedc','geartie6'] },
  { id:'urban', name:'City every day', blurb:'Office, transit, coffee, home.',
    items:['bm535','olbaton4','fisherbullet','bellrynote','seiko5snk','airpodspro','ankernano5k','airtag'] },
  { id:'outdoor', name:'Trail and truck', blurb:'Out of signal, back before dark.',
    items:['moracomp','zebrasc64','vicpioneerx','exonano','silvaranger','nalgene32','catgen7','paracord10','fox40whistle'] },
  { id:'grail', name:'No budget', blurb:'What people build when money stops mattering.',
    items:['spypara3','sfstiletto','ttsideclick','eksteralu','garmininst2','ncnb10000','ltfreep4','oakholbrook','peaktech'] },
  { id:'pocket', name:'Front pocket only', blurb:'Everything fits in one pocket at once.',
    items:['gerbsedge','rvaurora','vicclassic','bidtipocket','ccmicrowidgy','bicmini'] }
];

const CAT_BY_ID = Object.fromEntries(CATS.map(c => [c.id, c]));
const BY_ID = Object.fromEntries(PRODUCTS.map(p => [p.id, p]));
