/* Rewrites media/manifest.js from whatever is sitting in media/stills/.

   Browser storage holds a handful of pictures. A whole catalogue's worth
   belongs in the repo, where there is no quota, nothing is lost when
   someone clears their browser, and everyone opening a shared board sees
   the same thing. Drop the files in media/stills/, run this, done.

   A file is matched to a product the same way the app matches a dropped
   file: the product id outright (bm535.png), or a slug of the brand and
   name (benchmade-bugout-535.png). Anything unmatched is reported and
   left alone rather than guessed at.

   Run: node tools/edc-builder/scan-media.mjs                           */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { dirname, join, extname, basename } from 'path';
import { fileURLToPath } from 'url';

const here = dirname(fileURLToPath(import.meta.url));
const stills = join(here, 'media', 'stills');
const manifest = join(here, 'media', 'manifest.js');

const OK = new Set(['.png', '.webp', '.jpg', '.jpeg', '.avif', '.gif', '.svg']);
const slug = s => String(s).toLowerCase().replace(/[^a-z0-9]+/g, '');

/* The catalogue is plain data with no imports, so it can just be run. */
const src = readFileSync(join(here, 'js', 'catalog.js'), 'utf8');
const { PRODUCTS } = new Function(src + '; return { PRODUCTS };')();

const byId = new Map(PRODUCTS.map(p => [p.id, p]));
const bySlug = new Map();
PRODUCTS.forEach(p => {
  bySlug.set(slug(p.id), p.id);
  bySlug.set(slug(p.brand + p.name), p.id);
  if (!bySlug.has(slug(p.name))) bySlug.set(slug(p.name), p.id);
});

function match(file) {
  const base = basename(file, extname(file));
  if (byId.has(base)) return base;
  const want = slug(base);
  if (bySlug.has(want)) return bySlug.get(want);
  for (const [s, id] of bySlug) if (s.length > 6 && want.includes(s)) return id;
  return null;
}

if (!existsSync(stills)) {
  console.error('no media/stills/ folder — nothing to scan');
  process.exit(1);
}

const files = readdirSync(stills).filter(f => OK.has(extname(f).toLowerCase())).sort();
const hits = new Map();          /* id -> filename */
const missed = [];
const clashes = [];

files.forEach(f => {
  const id = match(f);
  if (!id) return missed.push(f);
  if (hits.has(id)) return clashes.push(f + ' also matches ' + id + ', already taken by ' + hits.get(id));
  hits.set(id, f);
});

const entries = [...hits.entries()].sort((a, b) => a[0].localeCompare(b[0]));
const body = entries.length
  ? entries.map(([id, f]) => `  ${JSON.stringify(id)}: ${JSON.stringify('stills/' + f)}`).join(',\n')
  : '';

writeFileSync(manifest, `/* =====================================================================
   EDC Builder - the media library
   ---------------------------------------------------------------------
   GENERATED by scan-media.mjs from the contents of media/stills/.
   Do not edit by hand: drop files in that folder and run

     node tools/edc-builder/scan-media.mjs

   Each entry replaces one product's drawing with an image, everywhere -
   catalogue card, pack list and board. Files are matched by name: the
   product id (bm535.png), or a slug of the brand and name
   (benchmade-bugout-535.png).

   For an image to sit with the drawings around it, cut the background
   out, shoot or generate square-on, and light from the top left. Trim it
   to the object's own edges too: the board fits an image inside the
   product's real millimetre footprint, so a knife centred in a square of
   empty space gets drawn at a third of its true size.

   The app's own picture drop zone does all of that on the way in - this
   file is for images that have already been prepared.

   Pictures a viewer adds in the browser sit on top of whatever is here,
   and removing one reveals this again.

   Empty is the normal state. Nothing here is required.
   ===================================================================== */
window.EDC_MEDIA = {${entries.length ? '\n' + body + '\n' : ''}};
`);

console.log(`media/stills: ${files.length} image file${files.length === 1 ? '' : 's'}`);
console.log(`matched to products: ${entries.length}`);
if (missed.length) {
  console.log(`\nno product matched (left out of the manifest):`);
  missed.forEach(f => console.log('  ' + f));
  console.log('\nrename these to a product id, or to the brand and name run together.');
}
if (clashes.length) {
  console.log('\nmore than one file wanted the same product:');
  clashes.forEach(c => console.log('  ' + c));
}
console.log(`\nwrote media/manifest.js`);
if (entries.length) console.log('rebuild the bundle: node tools/edc-builder/build-single.mjs');
